from datetime import datetime, timedelta
from typing import Any, Union, Optional
from cryptography.fernet import Fernet
import jwt
from jwt import PyJWTError as JWTError
import bcrypt
from app.core.config import settings

# Fernet encryptor initialization for credentials storage
# The encryption key MUST be a valid base64 key generated by Fernet
try:
    fernet = Fernet(settings.ENCRYPTION_KEY.encode())
except Exception as e:
    # Safe fallback for setup / migration states if key is not configured or invalid
    fernet = None

def encrypt_credential(plain_text: str) -> str:
    """
    Encrypt sensitive data (e.g. passwords, API keys) using Fernet.
    Returns a secure base64 string.
    """
    if not plain_text:
        return ""
    if not fernet:
        raise ValueError("Fernet Encryption Key is invalid or not set in environment.")
    return fernet.encrypt(plain_text.encode()).decode()

def decrypt_credential(cipher_text: str) -> str:
    """
    Decrypt credentials stored in database.
    """
    if not cipher_text:
        return ""
    if not fernet:
        raise ValueError("Fernet Encryption Key is invalid or not set in environment.")
    return fernet.decrypt(cipher_text.encode()).decode()

def verify_password(plain_password: str, hashed_password: str) -> bool:
    """
    Verify user login password against stored bcrypt hash using native bcrypt.
    """
    try:
        return bcrypt.checkpw(plain_password.encode('utf-8'), hashed_password.encode('utf-8'))
    except Exception:
        return False

def get_password_hash(password: str) -> str:
    """
    Generate secure bcrypt hash of password using native bcrypt.
    """
    return bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

def create_access_token(subject: Union[str, Any], expires_delta: Optional[timedelta] = None) -> str:
    """
    Generate JWT access token for API authorization.
    """
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=settings.ACCESS_TOKEN_EXPIRE_MINUTES)
    
    to_encode = {"exp": expire, "sub": str(subject)}
    encoded_jwt = jwt.encode(to_encode, settings.JWT_SECRET_KEY, algorithm=settings.JWT_ALGORITHM)
    return encoded_jwt

def decode_access_token(token: str) -> Optional[str]:
    """
    Decode and validate a JWT access token.
    Returns the token subject (e.g. user_id) if valid, or None.
    """
    try:
        payload = jwt.decode(token, settings.JWT_SECRET_KEY, algorithms=[settings.JWT_ALGORITHM])
        return payload.get("sub")
    except JWTError:
        return None
